var express = require("express");
var router = express.Router();
const { signup ,signin} = require("../controllers/auth");
const {checkStudentSessions} = require("../controllers/session");
const {getAllStudents,getUserById,getInstructorById,getAUser,getAllUsers} = require("../controllers/users")
const {checkAccess} = require("../controllers/auth")


// middlewares

router.param("userId" , getUserById )

router.param("instructorId" , getInstructorById)


// all auth and user related routes



//auth route for signup

router.post("/signup",signup);

//auth route for signin

router.post( "/signin", signin  );

//public route to get all students

router.get("/getallstudents",getAllStudents)

//public route to get a user by passing his ID

router.get("/getauser/:userId", getAUser)

//protected route to get all users by passing instructor ID

router.get("/getallusers/:instructorId" , checkAccess , getAllUsers )

//public route to get all student sessions by passing student Id

router.get("/checkStudentSessions/:userId" , checkStudentSessions );







// Swagger for Signup



/**
*   @swagger
*    components:
*      schemas:
*        Register:
*          type: object
*          required:
*            - name
*            - email
*            - password
*            - role
*          properties:
*            role:
*              type: integer
*              description: Enter role as 1 if you are an instructor and 0 if you are a student
*            name:
*              type: string
*              description: Enter your name.
*            email:
*              type: string
*              description: Enter email address
*            password:
*              type: string
*              description: Enter password here.
*          example:
*             role : 0
*             name : bob
*             email : bob@gmail.com
*             password : password
*/


/**
 * @swagger
 * /api/signup:
 *   post:
 *     summary: Route for regisering a user , passing role as 1 if you are an Instructor and 0 if you are a student.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Register'
  *     responses:
 *       200:
 *         description: Successfully regsitered.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 data:
 *                     type: object
 *                     properties:
 *                       role:
 *                         type: integer
 *                         description: user's role 1 if instructor and 0 if student.
 *                         example: 0
 *                       _id:
 *                         type: string
 *                         description: Id generated by mongoDB.
 *                         example: 609ec4b3aa111c1d3c1a016b
 *                       name:
 *                         type: string
 *                         description: user name.
 *                         example: bob
 *                       salt:
 *                         type: string
 *                         description: Secret for Security.
 *                         example: b73fd738-f22e-4d63-85f6-24259a56af76
 *                       encry_password:
 *                         type: string
 *                         description: Encrypted password.
 *                         example: e0d40a51514e20a68f14c42b4620a480ae4b6bf760c2fc026fcbfddde104a9a4
 *                       email:
 *                         type: string
 *                         description: The student's name.
 *                         example: bob@gmail.com
 *                       createdAt:
 *                         type: string                      
 *                         example: 2021-05-13T18:24:42.198Z
 *                       updatedAt:
 *                         type: string                      
 *                         example: 2021-05-14T16:22:21.198Z
*/    




// Swagger for signin





/**
*   @swagger
*    components:
*      schemas:
*        Signin:
*          type: object
*          required:
*            - email
*            - password
*          properties:
*            email:
*              type: string
*              description: Enter email address
*            password:
*              type: string
*              description: The date of the record creation.
*          example:
*             email : bob@gmail.com
*             password : password
*/


/**
 * @swagger
 * /api/signin:
 *   post:
 *     summary: Route for Signing in.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Signin'
  *     responses:
 *       200:
 *         description: Successfully signed in.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 * 
 *                 user:
 *                     type: object
 *                     properties:
 *                       role:
 *                         type: integer
 *                         description: user's role 1 if instructor and 0 if student.
 *                         example: 0
 *                       _id:
 *                         type: string
 *                         description: Id generated by mongoDB.
 *                         example: 609ec4b3aa111c1d3c1a016b
 *                       name:
 *                         type: string
 *                         description: user name.
 *                         example: bob
 *                       encry_password:
 *                         type: string
 *                         description: Encrypted password.
 *                         example: e0d40a51514e20a68f14c42b4620a480ae4b6bf760c2fc026fcbfddde104a9a4
 *                       email:
 *                         type: string
 *                         description: The student's name.
 *                         example: bob@gmail.com

*/ 











// Swagger to get all students





/**
 * @swagger
 * /api/getallstudents:
 *   get:
 *     summary: Public route to get all the students.
 *     description: Retrieve a list of users from JSONPlaceholder. Can be used to populate a list of fake users when prototyping or testing an API.
 *     responses:
 *       200:
 *         description: all users detail.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 data:
 *                   type: array
 *                   items:
 *                     type: object
 *                     properties:
 *                       _id :
 *                         type : string
 *                         example : 609ec4b3aa111c1d3c1a016b 
 *                       name:
 *                         type: string
 *                         description: student name.
 *                         example: Rob
 *                       email:
 *                         type: string
 *                         description: The student's name.
 *                         example: rob@gmail.com
 */




// Swagger to get a user





/**
 * @swagger
 * /api/getauser/{userId}:
 *   get:
 *     summary: Route to get details of a user by passing his ID.
 *     description: Retrieve a single JSONPlaceholder user. Can be used to populate a user profile when prototyping or testing an API.
 *     parameters:
 *       - in: path
 *         name: userId
 *         required: true
 *         description: Enter User ID.
 *         schema:
 *           type: string
  *     responses:
 *       200:
 *         description: Details of user.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 data:
 *                     type: object
 *                     properties:
 *                       role:
 *                         type: integer
 *                         description: user's role 1 if instructor and 0 if student.
 *                         example: 0
 *                       _id:
 *                         type: string
 *                         description: Id generated by mongoDB.
 *                         example: 609ec4b3aa111c1d3c1a016b
 *                       name:
 *                         type: string
 *                         description: user name.
 *                         example: bob
 *                       salt:
 *                         type: string
 *                         description: Secret for Security.
 *                         example: b73fd738-f22e-4d63-85f6-24259a56af76
 *                       encry_password:
 *                         type: string
 *                         description: Encrypted password.
 *                         example: e0d40a51514e20a68f14c42b4620a480ae4b6bf760c2fc026fcbfddde104a9a4
 *                       email:
 *                         type: string
 *                         description: The student's name.
 *                         example: rob@gmail.com
 *                       createdAt:
 *                         type: string                      
 *                         example: 2021-05-13T18:24:42.198Z
 *                       updatedAt:
 *                         type: string                      
 *                         example: 2021-05-14T16:22:21.198Z
 */




// Swagger to get all users by passing instructor ID







/**
 * @swagger
 * /api/getallusers/{instructorId}:
 *   get:
 *     summary: This is a protected route which can only be accesed by the instructor by providing his Id.
 *     description: Retrieve a single JSONPlaceholder user. Can be used to populate a user profile when prototyping or testing an API.
 *     parameters:
 *       - in: path
 *         name: instructorId
 *         required: true
 *         description: Instructor ID.
 *         schema:
 *           type: string
 *     responses:
 *       200:
 *         description: all users detail.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 data:
 *                   type: array
 *                   items:
 *                     type: object
 *                     properties:
 *                       role:
 *                         type : number
 *                         example : 0  
 *                       _id :
 *                         type : string
 *                         example : 609ec4b3aa111c1d3c1a016b 
 *                       name:
 *                         type: string
 *                         description: student name.
 *                         example: Rob
 *                       email:
 *                         type: string
 *                         description: The student's name.
 *                         example: rob@gmail.com
 */




// Swagger to get all student sessions in which he is registered in by passing Student Id





/**
 * @swagger
 * /api/checkStudentSessions/{StudentId}:
 *   get:
 *     summary: Check all the sessions in which the student is regsitered in and corresponding instructor name.
 *     description: Retrieve a single JSONPlaceholder user. Can be used to populate a user profile when prototyping or testing an API.
 *     parameters:
 *       - in: path
 *         name: StudentId
 *         required: true
 *         description: Student ID.
 *         schema:
 *           type: string
  *     responses:
 *       200:
 *         description: A list of sessions for which student has regsitered.
 *         content:
 *           application/json:
  *             schema:
 *               type: object
 *               properties:
 *                 data:
 *                     type: object
 *                     properties:
 *                       studentsAttending:
 *                         type: array
 *                         example: ["Bala,Rakesh"]
 *                       _id:
 *                         type: string
 *                         example: 60a03eb30c4e011510174d9d
 *                       topic:
 *                         type: string
 *                         example: maths
 *                       date:
 *                         type: string
 *                         example: 14/05/1999
 *                       startTime:
 *                         type: string
 *                         example: 6:30
 *                       duration:
 *                         type: string
 *                         example: 1hr
 *                       instructor:
 *                         type: string
 *                         example: Pramod
 *                       __v:
 *                         type: integer
 *                         example: 0
 */







module.exports = router;